/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DNT_H_RPCGEN
#define _DNT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DNT_PROG 0x4572879
#define DNT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define STR_DATE 1
extern  char ** str_date_1(long *, CLIENT *);
extern  char ** str_date_1_svc(long *, struct svc_req *);
extern int dnt_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STR_DATE 1
extern  char ** str_date_1();
extern  char ** str_date_1_svc();
extern int dnt_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DNT_H_RPCGEN */
