/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dnt.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	time_t now;
	time(&now);
	printf("Sending present date and time to client i.e., : %s", ctime(&now));
	result = ctime(&now);

	return &result;
}
